CREATE TABLE  "MY_ANXIETY" 
   (    "ANX_ID" NUMBER(20,0) NOT NULL ENABLE, 
    "ANX_SIT_ID" NUMBER(20,0) NOT NULL ENABLE, 
    "ANX_SUDS" NUMBER(10,0), 
    "ANX_TIMESTAMP" VARCHAR2(255), 
    "ANX_TIME" NUMBER(10,0), 
    "ANX_CREATED_BY" VARCHAR2(200), 
    "ANX_CREATED_DATE" DATE, 
    "ANX_USER_ID" NUMBER(20,0), 
    "ANX_INSTANCE_ID" VARCHAR2(255), 
    "ANX_COMMENT" VARCHAR2(4000), 
    "ANX_USERNAME" VARCHAR2(255), 
     CONSTRAINT "MY_ANXIETY_PK" PRIMARY KEY ("ANX_ID") ENABLE
   )
/
CREATE TABLE  "MY_CATEGORY" 
   (    "CAT_ID" NUMBER(20,0), 
    "CATEGORY_NAME" VARCHAR2(200), 
    "CATEGORY_DESCRIPTION" VARCHAR2(4000), 
    "CREATED_DATE" DATE, 
    "CREATED_BY" VARCHAR2(400), 
    "LAST_UPDATED_DATE" DATE, 
    "LAST_UPDATED_BY" VARCHAR2(400), 
     CONSTRAINT "MY_CATEGORY_PK" PRIMARY KEY ("CAT_ID") ENABLE
   )
/
CREATE TABLE  "MY_DIARY" 
   (    "ID" NUMBER, 
    "USERNAME" VARCHAR2(255), 
    "ENTRY" VARCHAR2(4000), 
    "DAT_TIME" VARCHAR2(255), 
     CONSTRAINT "MY_DIARY_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "MY_SITUATIONS" 
   (    "SIT_ID" NUMBER(20,0) NOT NULL ENABLE, 
    "SIT_NAME" VARCHAR2(200), 
    "SIT_DESCRIPTION" VARCHAR2(2000), 
    "SIT_DATE" DATE, 
    "SIT_TYPE" NUMBER(20,0), 
    "CREATED_BY" VARCHAR2(200), 
    "CREATED_DATE" DATE, 
    "LAST_UPDATED_BY" VARCHAR2(200), 
    "LAST_UPDATED_DATE" DATE, 
    "SIT_USER_ID" VARCHAR2(255), 
    "SIT_LEVEL" NUMBER, 
     CONSTRAINT "MY_SITUATIONS_PK" PRIMARY KEY ("SIT_ID") ENABLE
   )
/
CREATE TABLE  "MY_SUDS" 
   (    "ID" NUMBER(20,0), 
    "USER_ID" VARCHAR2(255), 
    "SUDS_LEVEL" NUMBER(20,0), 
    "SITUATION" VARCHAR2(4000), 
    "CREATED_BY" VARCHAR2(200), 
    "CREATED_DATE" DATE, 
    "LAST_UPDATED_BY" VARCHAR2(200), 
    "LAST_UPDATED_DATE" DATE, 
    "COLOUR" VARCHAR2(255), 
     CONSTRAINT "MY_SUDS_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "MY_TYPE" 
   (    "TYPE_ID" NUMBER(20,0) NOT NULL ENABLE, 
    "TYPE_NAME" VARCHAR2(400), 
    "TYPE_DESCRIPTION" VARCHAR2(2000), 
     CONSTRAINT "MY_TYPE_PK" PRIMARY KEY ("TYPE_ID") ENABLE
   )
/
CREATE TABLE  "THERAPIST_MESSAGE" 
   (    "ID" NUMBER, 
    "USERNAME" VARCHAR2(255), 
    "MESSAGE" VARCHAR2(255), 
    "DATE_TIME" DATE, 
     CONSTRAINT "THERAPIST_MESSAGE_PK" PRIMARY KEY ("ID") ENABLE
   )
/
CREATE TABLE  "USERS" 
   (    "USER_ID" NUMBER(20,0) NOT NULL ENABLE, 
    "USER_NAME" VARCHAR2(4000), 
    "FIRST_NAME" VARCHAR2(4000), 
    "LAST_NAME" VARCHAR2(4000), 
    "EMAIL" VARCHAR2(4000), 
    "DOB" DATE, 
    "SEX" VARCHAR2(1), 
    "TITLE" VARCHAR2(100), 
    "PASSWORD" VARCHAR2(4000), 
    "THERAPIST_ID" NUMBER(10,0), 
    "CATEGORY_ID" NUMBER(20,0), 
    "TYPE__ID" NUMBER(20,0), 
     CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID") ENABLE
   )
/
CREATE UNIQUE INDEX  "MY_ANXIETY_PK" ON  "MY_ANXIETY" ("ANX_ID")
/
CREATE UNIQUE INDEX  "MY_CATEGORY_PK" ON  "MY_CATEGORY" ("CAT_ID")
/
CREATE UNIQUE INDEX  "MY_DIARY_PK" ON  "MY_DIARY" ("ID")
/
CREATE UNIQUE INDEX  "MY_SITUATIONS_PK" ON  "MY_SITUATIONS" ("SIT_ID")
/
CREATE UNIQUE INDEX  "MY_SUDS_PK" ON  "MY_SUDS" ("ID")
/
CREATE UNIQUE INDEX  "MY_TYPE_PK" ON  "MY_TYPE" ("TYPE_ID")
/
CREATE UNIQUE INDEX  "THERAPIST_MESSAGE_PK" ON  "THERAPIST_MESSAGE" ("ID")
/
CREATE UNIQUE INDEX  "USERS_PK" ON  "USERS" ("USER_ID")
/
 CREATE SEQUENCE   "USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "THERAPIST_MESSAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MY_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MY_SUDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MY_SITUATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MY_DIARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MY_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MY_ANXIETY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ANXIETY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_USERS" 
  before insert on "USERS"               
  for each row  
begin   
  if :NEW."USER_ID" is null then 
    select "USERS_SEQ".nextval into :NEW."USER_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_USERS" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_THERAPIST_MESSAGE" 
  before insert on "THERAPIST_MESSAGE"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "THERAPIST_MESSAGE_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_THERAPIST_MESSAGE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MY_TYPE" 
  before insert on "MY_TYPE"               
  for each row  
begin   
  if :NEW."TYPE_ID" is null then 
    select "MY_TYPE_SEQ".nextval into :NEW."TYPE_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_TYPE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MY_SUDS" 
  before insert on "MY_SUDS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "MY_SUDS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_SUDS" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MY_SITUATIONS" 
  before insert on "MY_SITUATIONS"               
  for each row  
begin   
  if :NEW."SIT_ID" is null then 
    select "MY_SITUATIONS_SEQ".nextval into :NEW."SIT_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_SITUATIONS" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MY_DIARY" 
  before insert on "MY_DIARY"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "MY_DIARY_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_DIARY" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MY_CATEGORY" 
  before insert on "MY_CATEGORY"               
  for each row  
begin   
  if :NEW."CAT_ID" is null then 
    select "MY_CATEGORY_SEQ".nextval into :NEW."CAT_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_CATEGORY" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MY_ANXIETY" 
  before insert on "MY_ANXIETY"               
  for each row  
begin   
  if :NEW."ANX_ID" is null then 
    select "MY_ANXIETY_SEQ".nextval into :NEW."ANX_ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MY_ANXIETY" ENABLE
/
